//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unit_Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Unit_Test.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///&quot;expand&quot;: &quot;editmeta,renderedFields,transitions,changelog,operations&quot;,
        ///&quot;id&quot;: &quot;17301&quot;,
        ///&quot;self&quot;: &quot;http://jira.oebb.at/jira/rest/api/2/issue/17301&quot;,
        ///&quot;key&quot;: &quot;ADM-13&quot;,
        ///&quot;fields&quot;: {
        ///&quot;summary&quot;: &quot;Wiki Erweiterung&quot;,
        ///&quot;progress&quot;: { &quot;progress&quot;: 0, &quot;total&quot;: 0 },
        ///&quot;issuetype&quot;: { &quot;self&quot;: &quot;http://jira.oebb.at/jira/rest/api/2/issuetype/7&quot;, &quot;id&quot;: &quot;7&quot;, &quot;description&quot;: &quot;Vorgang um Anforderungen an die abteilungsinterne Administration zu stellen.&quot;, &quot;iconUrl&quot;: &quot;http://jira.oebb.at/jira/images/icons/improvement.gif&quot;, &quot;name&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string plvs_374_bad_date {
            get {
                return ResourceManager.GetString("plvs-374-bad-date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///&quot;expand&quot;: &quot;editmeta,renderedFields,transitions,changelog,operations&quot;,
        ///&quot;id&quot;: &quot;14078&quot;,
        ///&quot;self&quot;: &quot;http://jira.oebb.at/jira/rest/api/2/issue/14078&quot;,
        ///&quot;key&quot;: &quot;EFB-88&quot;,
        ///&quot;fields&quot;: {
        ///&quot;summary&quot;: &quot;Tooltipp zur ZF-Kennung&quot;,
        ///&quot;progress&quot;: { &quot;progress&quot;: 0, &quot;total&quot;: 0 },
        ///&quot;issuetype&quot;: { &quot;self&quot;: &quot;http://jira.oebb.at/jira/rest/api/2/issuetype/3&quot;, &quot;id&quot;: &quot;3&quot;, &quot;description&quot;: &quot;Eine Aufgabe, die erledigt werden muss.&quot;, &quot;iconUrl&quot;: &quot;http://jira.oebb.at/jira/images/icons/task.gif&quot;, &quot;name&quot;: &quot;Aufgabe&quot;, &quot;subtask&quot;: false },
        ///&quot;vot [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string plvs_374_no_priority {
            get {
                return ResourceManager.GetString("plvs_374_no_priority", resourceCulture);
            }
        }
    }
}
