//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlassian.plvs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atlassian.plvs.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;text-align:center;font-size:10px;font-family:Arial;&quot;&gt;
        ///
        ///The Atlassian Connector for Microsoft Visual Studio is an Visual Studio package that lets you work&lt;br&gt;
        ///with the Atlassian products within your IDE. Now you don&apos;t have to switch between websites,&lt;br&gt;
        ///email messages and news feeds to see what&apos;s happening to your project and your code.&lt;br&gt;
        ///Instead, you can see the relevant &lt;a href=&quot;http://www.atlassian.com/software/jira/&quot;&gt;JIRA&lt;/a&gt; issues
        ///&lt;!--, 
        ///&lt;a href=&quot;http://www.atlassian.com/software/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string about_html {
            get {
                return ResourceManager.GetString("about_html", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap add_jira {
            get {
                object obj = ResourceManager.GetObject("add_jira", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Atlassian {
            get {
                object obj = ResourceManager.GetObject("Atlassian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap atlassian_538x235 {
            get {
                object obj = ResourceManager.GetObject("atlassian_538x235", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap atlassian_installer {
            get {
                object obj = ResourceManager.GetObject("atlassian_installer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;font-size:12px;font-family:Arial;&quot;&gt;
        ///
        ///&lt;div&gt;New Version of the connector is available: &lt;strong&gt;{0}&lt;/strong&gt;&lt;/div&gt;
        ///&lt;br&gt;
        ///&lt;div style=&quot;font-size:12px;&quot;&gt;Highlights of the new version:&lt;/div&gt;
        ///
        ///&lt;div style=&quot;font-size:10px;&quot;&gt;{1}&lt;/div&gt;
        ///
        ///&lt;div&gt;&lt;a href=&quot;{2}&quot;&gt;See full release notes&lt;/a&gt;&lt;/div&gt;
        ///
        ///&lt;/div&gt;.
        /// </summary>
        internal static string autoupdate_html {
            get {
                return ResourceManager.GetString("autoupdate_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create tool window..
        /// </summary>
        internal static string CanNotCreateWindow {
            get {
                return ResourceManager.GetString("CanNotCreateWindow", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap collapse_all {
            get {
                object obj = ResourceManager.GetObject("collapse_all", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style type=&quot;text/css&quot;&gt;
        ///.comment_header{
        ///	background: lightgrey;
        ///	width: 100%;
        ///	height: 1em;
        ///	padding: 0.2em 0.5em;
        ///	border-bottom: 1px dotted;
        ///	font-family: Arial;
        ///	font-size: 10pt;
        ///}
        ///
        ///.author {
        ///	position: relative;
        ///	float: left;
        ///	left: 1em;
        ///	font-weight: bold;
        ///}
        ///
        ///.date {
        ///	font-style: italic;
        ///	font-weight: normal;
        ///}
        ///
        ///.toggler {
        ///	position: relative;
        ///	float: right;
        ///	right: 1em;
        ///	cursor:pointer;
        ///}
        ///
        ///.comment_body {
        ///	background: white;
        ///	width: 100%;
        ///	font-family: Arial;
        ///	font-s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string comments_css {
            get {
                return ResourceManager.GetString("comments_css", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap edit {
            get {
                object obj = ResourceManager.GetObject("edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap edit_in_browser {
            get {
                object obj = ResourceManager.GetObject("edit_in_browser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap expand_all {
            get {
                object obj = ResourceManager.GetObject("expand_all", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap find_jira {
            get {
                object obj = ResourceManager.GetObject("find_jira", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap global_properties {
            get {
                object obj = ResourceManager.GetObject("global_properties", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ico_jira_custom_filter {
            get {
                object obj = ResourceManager.GetObject("ico_jira_custom_filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ico_jira_filter {
            get {
                object obj = ResourceManager.GetObject("ico_jira_filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ico_jira_preset_filter {
            get {
                object obj = ResourceManager.GetObject("ico_jira_preset_filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ico_jira_recent_issues {
            get {
                object obj = ResourceManager.GetObject("ico_jira_recent_issues", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ico_jira_saved_filter {
            get {
                object obj = ResourceManager.GetObject("ico_jira_saved_filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ide_plugin_16 {
            get {
                object obj = ResourceManager.GetObject("ide_plugin_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon ide_plugin_161 {
            get {
                object obj = ResourceManager.GetObject("ide_plugin_161", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ide_plugin_300 {
            get {
                object obj = ResourceManager.GetObject("ide_plugin_300", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon ide_plugin_32 {
            get {
                object obj = ResourceManager.GetObject("ide_plugin_32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues - JIRA.
        /// </summary>
        internal static string IssueDetailsToolWindowTitle {
            get {
                return ResourceManager.GetString("IssueDetailsToolWindowTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap jira_blue_16 {
            get {
                object obj = ResourceManager.GetObject("jira_blue_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap minus {
            get {
                object obj = ResourceManager.GetObject("minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap new_comment {
            get {
                object obj = ResourceManager.GetObject("new_comment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap open_in_ide {
            get {
                object obj = ResourceManager.GetObject("open_in_ide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pazu {
            get {
                object obj = ResourceManager.GetObject("pazu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon pazu_32 {
            get {
                object obj = ResourceManager.GetObject("pazu_32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pin_other {
            get {
                object obj = ResourceManager.GetObject("pin_other", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap plus {
            get {
                object obj = ResourceManager.GetObject("plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap projectsettings {
            get {
                object obj = ResourceManager.GetObject("projectsettings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search_jira {
            get {
                object obj = ResourceManager.GetObject("search_jira", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap status_plugin {
            get {
                object obj = ResourceManager.GetObject("status_plugin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap status_plugin1 {
            get {
                object obj = ResourceManager.GetObject("status_plugin1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style type=&quot;text/css&quot;&gt;
        ///.summary, .description { 
        ///	font-size:&quot;10pt&quot;;
        ///	font-family:&quot;Arial&quot;; 
        ///}
        ///
        ///.labelcolumn {
        ///	text-align:&quot;right&quot;;
        ///	padding-right:&quot;1em&quot;;
        ///	font-weight:&quot;bold&quot;;
        ///	vertical-align:&quot;top&quot;;
        ///}
        ///
        ///.labelsummary {
        ///	padding-bottom:&quot;1em&quot;;
        ///}
        ///
        ///&lt;/style&gt;
        ///.
        /// </summary>
        internal static string summary_and_description_css {
            get {
                return ResourceManager.GetString("summary_and_description_css", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap tab_jira {
            get {
                object obj = ResourceManager.GetObject("tab_jira", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script language=&quot;javascript&quot;&gt;
        ///	function toggle(id, controlid) {
        ///		var el = document.getElementById(id);
        ///		var state = el.style.display;
        ///		if (state == &apos;block&apos;) {
        ///			document.getElementById(id).style.display = &apos;none&apos;;
        ///			document.getElementById(controlid).innerHTML=&quot;expand&quot;;
        ///		} else {
        ///			document.getElementById(id).style.display = &apos;block&apos;;
        ///			document.getElementById(controlid).innerHTML=&quot;collapse&quot;;
        ///		}
        ///	}
        ///&lt;/script&gt;
        ///
        ///.
        /// </summary>
        internal static string toggler_javascript {
            get {
                return ResourceManager.GetString("toggler_javascript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atlassian.
        /// </summary>
        internal static string ToolWindowTitle {
            get {
                return ResourceManager.GetString("ToolWindowTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap unknown {
            get {
                object obj = ResourceManager.GetObject("unknown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap update_unavailable {
            get {
                object obj = ResourceManager.GetObject("update_unavailable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap view_in_browser {
            get {
                object obj = ResourceManager.GetObject("view_in_browser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
